Refactor cel2-migration-tool chart
celo-org/charts pull request #350
Opened 2024-07-10 14:11 UTC by rkachowski

This PR is an attempt at learning to refactor helm charts in a way that we are comfortable with. Starting with this repo as it is self contained and a one off job that is not regularly launched. Comments and suggestions on style and approach are appreciated

The main changes are

* using consistent values references for `alpine` containers
* import scripts via from discrete files in the `/templates/scripts` dir

also

* fix some typos

## Todo:

* identify secret values and replace with templating + k8s secrets
    * are rpc urls secrets?

## Discussion points

* is this way of handling script files something we want to have across all charts?

2024-07-16 08:49 UTC, alvarof2 commented on charts/cel2-migration-tool/templates/scripts/_migration.tpl
> +{{- end }}
Nickpick: since we are refactoring, I would change this block to
```yaml
  --batch-size {{ .Values.migrationTool.config.batchSize }}{{ if .Values.migrationTool.extraArgs }} \{{ end }}
  {{- $length := len .Values.migrationTool.extraArgs }}
  {{- range $index, $value := .Values.migrationTool.extraArgs }}
  {{ tpl $value $ }}{{ if lt $index (sub $length 1) }} \{{ end }}
  {{- end }}
```

To properly treat backslashes.

Note that two spaces `  ` are needed nevertheless in lines 13,14 and 15 for indentation in any case.

2024-07-16 08:58 UTC, alvarof2 commented
As for questions:

- are rpc urls secrets? -> I would say yes iff the URL contains an API key

- is this way of handling script files something we want to have across all charts? -> I think it's a good idea. May be overkill for some cases, I'm thinking of env. var substitution for secrets like in [proxyd chart](https://github.com/celo-org/charts/blob/d4e5e6e3a15574817750fcdddfd89999b7cc3d54/charts/op-proxyd/templates/deployment.yaml#L39):
```yaml
      containers:
        - name: {{ .Chart.Name }}
          command: 
            - /bin/bash
            - -c
          args: 
            - |
              envsubst < /etc/proxyd/proxyd-tmp.toml > /etc/proxyd/proxyd.toml
              /bin/entrypoint.sh /bin/proxyd /etc/proxyd/proxyd.toml
```

But guessing this is something we have to go case by case.

2024-07-16 08:59 UTC, alvarof2 requested changes

2024-07-16 08:59 UTC, alvarof2 commented on charts/cel2-migration-tool/templates/scripts/_migration.tpl
> +{{- end }}
Two spaces `  ` needed here for indentation.

2024-07-16 09:01 UTC, alvarof2 commented on charts/cel2-migration-tool/templates/scripts/_migration.tpl
> +tail -f /dev/null
This is a hack we were using to avoid the CronJob continue and run the `compress-and-upload` container. Dunno if we would like to keep it or make it actionable (like with an if).

2024-07-16 11:18 UTC, lvpeschke commented
Thanks for diving into this! Once discussions are settled, it would be nice to update the best practices here: https://github.com/celo-org/charts/blob/main/docs/helm-best-practices.md

2024-07-16 12:17 UTC, rkachowski commented
> I'm thinking of env. var substitution for secrets like in [proxyd chart](https://github.com/celo-org/charts/blob/d4e5e6e3a15574817750fcdddfd89999b7cc3d54/charts/op-proxyd/templates/deployment.yaml#L39):
> 
> ```yaml
>       containers:
>         - name: {{ .Chart.Name }}
>           command: 
>             - /bin/bash
>             - -c
>           args: 
>             - |
>               envsubst < /etc/proxyd/proxyd-tmp.toml > /etc/proxyd/proxyd.toml
>               /bin/entrypoint.sh /bin/proxyd /etc/proxyd/proxyd.toml
> ```
> 
> But guessing this is something we have to go case by case.

@alvarof2 

wrt how secrets are handled, @jcortejoso mentioned an approach of having a secret key reference + literal secret value override as a convention (if i understand correctly, [this is an example of that approach](https://github.com/celo-org/charts/blob/f73c40e7af6160c7636de7ffc6a65b1b12cba2b1/charts/op-node/templates/statefulset.yaml#L89) )

if we have a constant convention it should be possible to template the whole thing with a `common` function and that would help push us towards making us feel like the charts are "ours" (rather than just adhoc forks, as we talked about before)

2024-07-16 13:41 UTC, alvarof2 commented
> > I'm thinking of env. var substitution for secrets like in [proxyd chart](https://github.com/celo-org/charts/blob/d4e5e6e3a15574817750fcdddfd89999b7cc3d54/charts/op-proxyd/templates/deployment.yaml#L39):
> > ```yaml
> >       containers:
> >         - name: {{ .Chart.Name }}
> >           command: 
> >             - /bin/bash
> >             - -c
> >           args: 
> >             - |
> >               envsubst < /etc/proxyd/proxyd-tmp.toml > /etc/proxyd/proxyd.toml
> >               /bin/entrypoint.sh /bin/proxyd /etc/proxyd/proxyd.toml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But guessing this is something we have to go case by case.
> 
> @alvarof2
> 
> wrt how secrets are handled, @jcortejoso mentioned an approach of having a secret key reference + literal secret value override as a convention (if i understand correctly, [this is an example of that approach](https://github.com/celo-org/charts/blob/f73c40e7af6160c7636de7ffc6a65b1b12cba2b1/charts/op-node/templates/statefulset.yaml#L89) )
> 
> if we have a constant convention it should be possible to template the whole thing with a `common` function and that would help push us towards making us feel like the charts are "ours" (rather than just adhoc forks, as we talked about before)

Only thing I fear of a `common` function is that in the past, it has run to have so many exceptions that it's hell now, I mean the [common chart ](https://github.com/celo-org/charts/tree/main/charts/common)that is used as a dependency in e.g. the [testnet chart](https://github.com/celo-org/charts/blob/d4e5e6e3a15574817750fcdddfd89999b7cc3d54/charts/testnet/Chart.yaml#L26). But if it's kept for simple things like the secret handling it should be OK.


🙏 sorry about my comment, I think it was misleading. I was referring to just the two lines of 
```
          args: 
            - |
              envsubst < /etc/proxyd/proxyd-tmp.toml > /etc/proxyd/proxyd.toml
              /bin/entrypoint.sh /bin/proxyd /etc/proxyd/proxyd.toml
```

being considered a script or not. WRT secrets as env vars, the proxyd chart has the same approx. as others. The need for `envsubst` is because proxyd uses a toml config file `/etc/proxyd/proxyd.toml` for the process. The toml file can just be a plain text/configmap, but then we need to substitute the e.g. API keys into that file

For example the op-node chart parses the secret env var [with a script and puts its contents in a file](https://github.com/celo-org/charts/blob/f73c40e7af6160c7636de7ffc6a65b1b12cba2b1/charts/op-node/templates/scripts/_split-config-parameters.tpl#L8) and then just reads that file.

2024-07-16 13:49 UTC, jcortejoso commented
Referring to the secret discussion, some people for blockchain team suggested me that it'd be easier to the if the secret were provided explicitly as a cmdflag for components where secret can be provided by env var or by cmd flag. To illustrate this, if to op-batcher it's possible to set l1 url as `--l1-eth-rpc=` and using env var `$OP_BATCHER_L1_ETH_RPC`, they'd prefer to provide explicitly with the cmdflag (so it's easier to debug and check the config used for running). As a combination of both we could be in that case doubly explicit (setting `--l1-eth-rpc=$OP_BATCHER_L1_ETH_RPC`)

2024-07-16 15:15 UTC, rkachowski commented
thanks for the input :)

> I was referring to just the two lines of
> 
>           args: 
>             - |
>               envsubst < /etc/proxyd/proxyd-tmp.toml > /etc/proxyd/proxyd.toml
>               /bin/entrypoint.sh /bin/proxyd /etc/proxyd/proxyd.toml
> being considered a script or not

as a rule of thumb I would consider anything more than a few lines (lets say 5) of bash to be a script. if the functionality is both trivial and minimal there's not much to be gained by moving it out. additionally `proxyd` seems like a special case and I don't feel it would be helpful to fight against it's requirement to be provided a config file on startup - the same exceptions would apply to other services.

> Only thing I fear of a common function is that in the past, it has run to have so many exceptions that it's hell now

I wasn't aware of the history of the `common` chart, just saw that there was already a place for common functions. I'd also like to avoid having a junk drawer of disorganised commands, but as a location for functionality to enable a convention of secret handling across charts it would seem to make sense to put it there (unless there is a better mechanism?)

> some people for blockchain team suggested me that it'd be easier to the if the secret were provided explicitly as a cmdflag

this would imply

* prefer cmdline options over env vars (when both are available)
* be explicit about the source of cmdline options

2024-07-24 08:42 UTC, alvarof2 approved these changes

2024-07-24 09:28 UTC, jcortejoso approved these changes

2024-07-24 12:28 UTC, merged